version: "3"

vars:
  DB_URL: "postgres://{{.DB_URLS_USERNAME}}:{{.DB_URLS_PASSWORD}}@{{.DB_URLS_HOST}}:{{.DB_URLS_PORT}}/{{.DB_URLS_NAME}}?sslmode=disable"
  MIGRATIONS_PATH: "./migrations/postgres"

tasks:
  migrate-sql:
    aliases:
      - mig-sql
    desc: "migrates SQLite database"
    cmds:
      - migrate -path {{.MIGRATIONS_PATH}} -database "{{.DB_URL}}" up

  migrate-sql-down:
    aliases:
      - mig-sql-down
    desc: "rollback SQLite database"
    cmds:
      - migrate -path {{.MIGRATIONS_PATH}} -database "{{.DB_URL}}" down

