CREATE TABLE IF NOT EXISTS url (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    url TEXT NOT NULL,
    alias TEXT UNIQUE NOT NULL,
    user_id INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_alias ON url(alias);
CREATE INDEX IF NOT EXISTS idx_user_id ON url(user_id)

DROP INDEX IF EXISTS idx_user_id;
DROP INDEX IF EXISTS idx_alias;

DROP TABLE IF EXISTS url;